# todo
sudo: required
language: java
services:
  - docker

addons:
  sonarcloud:
    organization: "4admin2root-github"
    token:
      secure: "$SONAR_TOKEN"


before_install:
- docker pull 4admin2root/jdk:8

jdk:
  - oraclejdk8
#  - oraclejdk7
#  there is a bug in travis
#  JAVA_HOME is not defined correctly
#  $ jdk_switcher use oraclejdk7
#  Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
#  update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
   - mvn install -dmaven.test.skip=true
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker build . -t 4admin2root/cloud-simple-helloworld:latest
  - docker run -d --rm --name helloworld -p 8888:8080 4admin2root/cloud-simple-helloworld:latest 
  - sleep 30
  - curl --connect-timeout 20 --retry 5 --retry-delay 5 http://localhost:8888/ 
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push 4admin2root/cloud-simple-helloworld:latest;
    fi
