# todo
sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
- docker pull 4admin2root/maven:3.5


after_success:
  - docker build . -t 4admin2root/cloud-simple-helloworld:latest
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push 4admin2root/cloud-simple-helloworld:latest;
    fi
