apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloud-simple-helloworld
  name: cloud-simple-helloworld
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cloud-simple-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-simple-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-simple-helloworld
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: my-gitlab-redis
        image: 4admin2root/cloud-simple-helloworld:dev
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloud-simple-helloworld
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
